apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kibana-sso-proxy.fullname" . }}
  labels:
    {{- include "kibana-sso-proxy.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
